WSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an S3 Bucket
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: joes=drift-bucket
      AccessControl: Public
      Logging: Disabled 
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 365


            
